travis:
  secure:
    BINSTAR_TOKEN: JCCww9a2c9aMBAYaL9hlC7A2H69ioIelT8RvRo9od8BqKB0R/EHgYxMu/aErcnxpFdv6+aT9c62xro9TCAUKbChT+cSJlPkDUcA005R1RsZIqqiOITW+ERRBE9VZBy0mTVqNFvY/dCrAiV5vBQFb73TSlZSX9NpbiBDokJ48iGytP5xtthdLkiPUuxNy4zWTUSK6LC4O5S+FZYeL3RtCT7AmlHZyBJUEHidnNsbLwy2WcmvM7E3mukkAz92MQ8EXhe+hBcE3Ud0E2DRas+WbsuNspWMthKxaOhKQAgYH//staBY2ytKX4sKfpEoki+v4JwK3cvEjyI92/QRxx61GkB/ryI1e7ylVc6M1pw1n/UvTStudaataDSpUaeCnnwtdk4YYVQhaOIlbaQDZ7yYSRebIa4gScWs5iuKB5K3JpW6I873zYakUbz9kJ9xry0RTtbIXtlnWJCysJoUosPumCLGqYfkqotC42OfyeBtG5Ddk9cDHrwyoWVKsT/LZhtcROxNLZe9pKk4F8PS4Xo+MeSJqlCkocyeu2zLgcwAbMPxFFnGml2NmUBYMOVGpB55SLOfiaF81s/qE8hGnCFbJX0mLe/aPXak1VuU3shMuJLJ1+RbYzqdtX8UjK13opiPRjpcNis0zcbqglxN64sVN+/Nrd2a1+AmuRe/3fVoaRK0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
